### ISSUE TITLE
TrayIcon notification doesn't support unset hotkeys

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#126]
Should Sidekick's notification support the fact that the price checking and close overlay hotkeys are unset? If one of those is unset, Sidekick crashes.
Maybe we should add a setting to allow the user to disable notifications, I know some people hate this.
Right now, to unset a hotkey, just right-click on the button in the settings window.

**Comment by cmos12345** [comment]
I don't think there should be a notification since sidekick will have so many features, that people just might want to disable some. Why should sidekick bother them to also turn off notifications? 
I also think you can already disable a hotkey. Just click on the hotkey you want disabled and press save.

**Comment by domialex** [comment]
> I also think you can already disable a hotkey. Just click on the hotkey you want disabled and press save.

I know, I was just explaining how to unset hotkeys, I'll edit my description.

**Comment by domialex** [comment]
So we could just notify that "Sidekick is ready" without the body if the keys are unset.

**Comment by leMicin** [comment]
I think having the notification is a necessity. The people that download this tool will not always be advanced users. It is important to have some feedback by default to help all our users.

Though, I agree having an opt-out setting should be considered.
