### ISSUE TITLE
Scroll Position Doesn't Reset

### ISSUE THREAD

**Issue by eugenio-santos** [domialex/Sidekick#17]
The scroll position doesn't reset between events.

Don't  know if there's any more useful detail I can give.

**Comment by cmos12345** [comment]
Since the overlay is only hidden when the "ESC" button is pressed, all the parameters of the overlay (i.e scrollbar position, screen position size etc) are "stored" until the overlay will be shown again. 
Resetting the scrollposition of the of the ScrollViewer when the overlay is hidden should do the trick.
