### ISSUE TITLE
Roadmap - Version 1.0.0

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#286]
Our plan for the release of 1.0.0 is to release it for the Harvest league. If we cannot complete all the issues prior to league launch, we will make a 0.9.0 with all the stuff that will be ready.

To view the issues that we are tackling before the release of Sidekick:
https://github.com/domialex/Sidekick/milestone/7

**Comment by AwesomeFart** [comment]
Hello again - so i am following development for some time and i am really apreciating the work you guyz put in.
Since ppl like me dont rly go to your discord bcs they dont have rly anything to contribute and the only info source is kinda here i have a proposal / suggestion - can we get more detailed roadmap so we dont ask - can this be in, and when it could be in? Like i imagined 1.0 with trade macros and now it doesnt seem like it. i understand this is kinda wasting your time, but we would love to be informed.
Maybe a place where we can comment/discuss and dont be afraid to spam your "issues" page?
Maybe like a manifesto from devs, that we can freely comment on? Now it seems like 1.0 means what we have now + working item advanced filter. If that so - whats next? Are the same ppl gonna stick around for development?I personally feel like currency search is VERY much a placeholder for now and needs more  ( issue #91 ).

Thank you again and keep in mind we love you.

**Comment by leMicin** [comment]
Thank you so much for the kind words.

We are trying to keep you informed in the roadmaps, but roadmaps are never really final. For 0.6.0 we wanted to release a working version as soon as we could. That version is not complete which is why we are now planning a 0.7.0 to finish all features related to filters. We will probably have a 0.8.0 for a different currency result view.

If you have features that you want sooner, don't hesitate to comment on existing issues and/or create new ones. Issues are there for general conversation also. They are not necessirily 100% technical.

Thank you again!

**Comment by AwesomeFart** [comment]
Maybe i ment a little more big picture. I guess what i ment - can be better translated as "milestones". 
"Untill 1.0. we want to add these features:" = 1.0 Milestones
"These features are being added after 1.0.:" = 2.0. Milestones 
"We are considering to maybe add way later:" 

But i dont think its about what i as and individual want - thats why i thought it would be good idea if we have a space where we could all openly discuss that.

Altho, thank you for your explanation and keep up the great work!
