### ISSUE TITLE
Limit maximum requests in a given time

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#371]
This is now a priority since spamming the servers can be detected as malicious intent by GGG and lock accounts. This is happening a lot with POE-Overlay right now.
We need to add a debounce on requests and/or a search button.

Mentioned in #362.

**Comment by leMicin** [comment]
We send requests when we activate or deactivate a filter and when we focusout from a textfield. We do not have a way to more quickly change values such as sliders or scrollwheel, which would spam the server on every change.

I think adding a limit could be a good idea, but we are not spamming the servers the same way poe overlay is. Not even close.

I don't like the idea of a search button as it would desync the filters and the results. If I check a new filter and don't hit search, the results would not reflect the filters.

Here is my suggestion:
When we activate a new filter, the results must clear immediately. In the place of results, we add a counter (3... 2... 1..., SEARCH). With the counter, we add a Search now button to search right away and skip the wait (debounce).

I don't want the button in the filters column. I want the filters and results to remain synced, which is why I suggest to wipe the results when they don't sync anymore.

**Comment by domialex** [comment]
- No search button
- Clear results when we change a value
- Start a timer when values change
- Reset timer every time a value changes

The timer should actually use the progress bar we already have, maybe make it progressive from 100% to 0%, then put it back to `IsIndeterminate`.

![image](https://user-images.githubusercontent.com/4694217/80642248-244a4100-8a34-11ea-93f6-09838a118a4a.png)

**Comment by Silentguard** [comment]
> Here is my suggestion:
> When we activate a new filter, the results must clear immediately. In the place of results, we add a counter (3... 2... 1..., SEARCH). With the counter, we add a Search now button to search right away and skip the wait (debounce).
> 
> I don't want the button in the filters column. I want the filters and results to remain synced, which is why I suggest to wipe the results when they don't sync anymore.

Waiting countdown shouldn't be only option. Look on the button solution as on abstraction. I'am using click on result field to trigger TextField FocusOut, which is already works as "Search" button.

**Comment by leMicin** [comment]
There is also an alternative that I wrote: we add a Search now button to search right away and skip the wait. The wait is just there to not spam the servers. You will be able to wait or click the button to skip it.

**Comment by Silentguard** [comment]
I mean it's already works like a button.
![image](https://user-images.githubusercontent.com/13031465/81053473-b56b5d00-8ef7-11ea-98f5-78dde0c50bbd.png)
More obvious interaction.
