### ISSUE TITLE
Bug when oppening application(sometimes)

### ISSUE THREAD

**Issue by firespark1983** [domialex/Sidekick#470]
![image](https://user-images.githubusercontent.com/72697794/95680734-6af7b600-0be4-11eb-86f7-6b970e6a4704.png)
Usually program works without issues, but sometimes it will not start and have this error in windows logs, nothing is written in local program log.

Haven't found other solution then a system restart.

I have a windows 10 pro , OS version 2004(19041.508)

![image](https://user-images.githubusercontent.com/72697794/95680865-27ea1280-0be5-11eb-9598-022735cd1c66.png)

**Comment by domialex** [comment]
Hey thanks!
I'm currently, and slowly, trying to port the UI part of Sidekick to Electron. That would make it easier to package, install, auto-update, have a smaller memory footprint compared to WPF (believe it or not 😄), and would fix this problem.

I won't prioritize this since I'm not exactly sure what's causing the problem in the single-file release to stop being extracted in memory by Windows. Using the zipped version works for everyone it seems.

**Comment by Chiron1991** [comment]
I'm facing the exact same error as @firespark1983. However, for me the error only occurs when using the .exe bundle, not with the .zip version.

**Comment by domialex** [comment]
I'm thinking I might just remove the .exe file, it's causing problems for everyone. .NET 5 might fix this unpacking problem in the future from what I've read.

**Comment by leMicin** [comment]
With the new initialization flow in 1.2.0, this should be fixed.
