### ISSUE TITLE
Can't price check organs

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#601]

**Comment by kihoon0224** [comment]
me either.
UI Language : Eng / Gmae Language : Kor
Key Bind Doesn't work.  Price Check Doesn't Work Too. Ver. 2.1.0

**Comment by 5c0r** [comment]
```
Item Class: Metamorph Sample
Rarity: Unique
Portentia, the Foul's Heart
--------
Uses: Blood Bubble
--------
Item Level: 79
--------
Drops additional Rare Jewellery
Drops additional Currency Items
Drops additional Currency Items
Drops additional Rare Weapons
Drops additional Rare Armour
--------
Combine this with four other different samples in Tane's Laboratory.

```

So this is what MetadataProvider returned
```
Type: Portentia, the Foul
Category: ItemizedMonster
Rarity: Unique
```

As the item is unique , the ItemizedMonster entry was used for the query instead of the full name. 
For price checking bestiary and metamorph, it is better to use the full name IMO.

Have something working already, let's see if I can have a cleaner approach

**Comment by leMicin** [comment]
Moved to https://github.com/Sidekick-Poe/Sidekick/issues/6
